### PR TITLE
client generation with minor fixes in the API spec

### PR DESCRIPTION
**Pull request by tivvit**

### CODE REVIEW

**Comment by tivvit** [comment]
Maybe 403 was to mark season end?

**Comment by tivvit** [comment]
> 

yeah, I think we agreed on that. Sorry I will fix that

**Comment by tivvit** [comment]
fixed

**Comment by tivvit** [comment]
@evamayerova I need 2 things:
* Can you please change the definition to be able to generate the Python client (using the code provided in this MR)
* Can you please add some description of what status 403 means? That for login it has the default meaning and for all other cases it means please login again (for various reasons - new season, lost session)

**Comment by evamayerova** [comment]
> @evamayerova I need 2 things:
> 
> * Can you please change the definition to be able to generate the Python client (using the code provided in this MR)
> * Can you please add some description of what status 403 means? That for login it has the default meaning and for all other cases it means please login again (for various reasons - new season, lost session)

@tivvit Done.

**Comment by tivvit** [comment]
thanks

**Pull request merged**
