### PR TITLE
min-time-left-ms

### PR DESCRIPTION
**Pull request by tivvit**
return `min-time-left-ms` which marks when the update cycle starts (freeze the table, and everything will be moved to a new season because of transaction), when a player wants to get reliably to the next tick `end-turn` should be used

### CODE REVIEW

**Comment by malytomas** [comment]
what issues have you experienced in the previous implementation to warrant these changes?
in the browser i use the time-left-ms to wait to issue new request and it seemed to work well...

**Comment by tivvit** [comment]
> what issues have you experienced in the previous implementation? I use the time-left-ms in the browser to wait to issue new request, and it seems to work well...

I saw you do. Your implementation counts a lot with the static timing, it could be more flexible with end-time (for dev servers). But that is for discussion the MR.

The point is that we are not able to tell what is `time-left` in this tick because we do not know how long the update is going to take (making it very unreliable). Therefore this just returns the first time when it may be updated (when the update is called).

**Review by curusarn — APPROVED** [review]
lgtm

**Review by curusarn — APPROVED** [review]
lgtm

**Pull request merged**
